### PR TITLE
Backpacks, ComputerCraft, Enchanting Plus, Version Checker Update

### PR DESCRIPTION
**Pull request by kraineff**

### CODE REVIEW

**Comment by kraineff** [comment]
@Iclario can you add Download Button - FaithfulME 1.8 on f32.me

**Comment by Farossco** [comment]
Yep, I will try but I'm not sure of the result :)

**Comment by Farossco** [comment]
I just eddited the script to process 1.8 pack, we should ask @DZCreeper about how to edit the page (I think that the 1.6  pack should go with the olders pack).

I will make a pull request and wait for his answer.

**Comment by Farossco** [comment]
Ok, actually, I don't have write acess to siteF32 and buildF32 repositories and there is many pull requests waiting in siteF32, so, I will wait for @DZCreeper to answer before doing anything.

**Pull request merged**
