### PR TITLE
SmartMoving, IronChest, Baubles, ProjectE, ThaumicTinkerer, Capsule Update

### PR DESCRIPTION
**Pull request by kraineff**

### CODE REVIEW

**Comment by ghost** [comment]
Are you just importing the 1.7 stuff or is this 1.8 stuff only?

Either way, please label the mod version supported in MODSUPPORT.md.

**Comment by kraineff** [comment]
No, i check all new textures. And i add it in MODSUPPORT.md

**Comment by kraineff** [comment]
Thats all today)

**Comment by ghost** [comment]
Appreciate it :)

What I mean by label the mod version is something like Thaumcraft 5.0.2 instead of just saying Thaumcraft. Less confusing for everyone.

**Comment by kraineff** [comment]
Oh ok. Tomorrow. I make new PL if you merge it now. Or fix in this request

**Comment by kraineff** [comment]
@DZCreeper you can merge it now)

**Pull request merged**
